-- Revenue generated by each landing page. 
CREATE VIEW LANDING_PAGE_REVENUE AS
WITH PAGEVIEW_COUNT AS (
SELECT website_session_id,
pageview_url,
created_at,
COUNT(*) AS Total_views
FROM website_pageviews wp 
GROUP BY website_session_id, pageview_url,
created_at),
LANDING_PAGEVIEW AS (SELECT
website_session_id,
pageview_url AS Landing_url
FROM ( 
SELECT *,
ROW_NUMBER() OVER (PARTITION BY website_session_id ORDER BY created_at ASC) AS rn
FROM PAGEVIEW_COUNT) sub WHERE rn = 1)
SELECT Landing_url,
COUNT(DISTINCT o.order_id) AS total_orders,
SUM(o.price_usd) AS total_revenue
FROM LANDING_PAGEVIEW lp
LEFT JOIN orders o
ON lp.website_session_id = o.website_session_id 
GROUP BY Landing_url 
ORDER BY total_revenue DESC